'use client';

import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Binary, Calculator, Lightbulb, TrendingUp } from 'lucide-react';

interface MathConcept {
  id: string;
  title: string;
  subtitle: string;
  formula: string;
  latexDoc: string;
  latexDisplay: string;
  description: string;
  institutionalUtility: string;
  params: { name: string; desc: string }[];
  interactiveDemo?: {
    label: string;
    inputs: { name: string; min: number; max: number; step: number; default: number; symbol: string }[];
    calc: (vals: Record<string, number>) => { result: number | string; label: string; interpretation: string };
  };
}

const CONCEPTS: MathConcept[] = [
  {
    id: 'obi',
    title: 'Order Book Imbalance (OBI)',
    subtitle: 'Level-1 to Level-10 Depth Pressure Ratio',
    formula: 'OBI_t = (V_b - V_a) / (V_b + V_a)',
    latexDoc: '\\text{OBI}_t = \\frac{V_t^b - V_t^a}{V_t^b + V_t^a}',
    latexDisplay: 'OBI_t = \\frac{V_t^b - V_t^a}{V_t^b + V_t^a}',
    description: 'Measures net buying vs selling pressure across top order book levels normalized between -1.0 (pure offer pressure) and +1.0 (pure bid pressure).',
    institutionalUtility: 'Triggers sub-millisecond front-running liquidity signals when |OBI| > 0.65 with low bid-ask spread variance.',
    params: [
      { name: 'V_t^b', desc: 'Total bid volume aggregated across specified depth levels L1..L10' },
      { name: 'V_t^a', desc: 'Total ask (offer) volume aggregated across depth levels L1..L10' },
    ],
    interactiveDemo: {
      label: 'OBI Interactive Calculator',
      inputs: [
        { name: 'bidVol', min: 100, max: 50000, step: 100, default: 12500, symbol: 'Bid Vol (V_b)' },
        { name: 'askVol', min: 100, max: 50000, step: 100, default: 4200, symbol: 'Ask Vol (V_a)' },
      ],
      calc: (vals) => {
        const b = vals.bidVol || 0;
        const a = vals.askVol || 0;
        const obi = (b - a) / (b + a);
        let status = 'Neutral Drift';
        if (obi > 0.35) status = 'Bullish Order Flow (Bids Dominant)';
        else if (obi < -0.35) status = 'Bearish Pressure (Offers Dominant)';
        return {
          result: obi.toFixed(4),
          label: 'OBI Value',
          interpretation: status,
        };
      },
    },
  },
  {
    id: 'vpin',
    title: 'Volume-Synchronized Probability of Toxicity (VPIN)',
    subtitle: 'Easley-Lopez de Prado Informed Trading Metric',
    formula: 'VPIN = sum(|V_B - V_S|) / (N * V)',
    latexDoc: '\\text{VPIN} = \\frac{\\sum_{\\tau=1}^N |V_\\tau^B - V_\\tau^S|}{N \\cdot V}',
    latexDisplay: 'VPIN = \\frac{\\sum_{\\tau=1}^N |V_\\tau^B - V_\\tau^S|}{N \\cdot V}',
    description: 'Calculates the fraction of total volume generated by informed traders over equal-volume buckets, detecting impending flash crashes and adverse selection.',
    institutionalUtility: 'Dynamic risk management: automatically reduces market making inventory sizes when VPIN exceeds 0.72.',
    params: [
      { name: 'V_\\tau^B', desc: 'Buy-initiated volume in volume bucket tau (classified via Tick Rule or Bulk Volume Classification)' },
      { name: 'V_\\tau^S', desc: 'Sell-initiated volume in volume bucket tau' },
      { name: 'N', desc: 'Number of historical volume buckets in rolling window (e.g. N = 50)' },
      { name: 'V', desc: 'Constant bucket volume size (e.g. 1/50th of average daily volume)' },
    ],
    interactiveDemo: {
      label: 'VPIN Toxicity Calculator',
      inputs: [
        { name: 'buyVol', min: 1000, max: 20000, step: 500, default: 14000, symbol: 'Buy Bucket Vol' },
        { name: 'sellVol', min: 1000, max: 20000, step: 500, default: 4000, symbol: 'Sell Bucket Vol' },
      ],
      calc: (vals) => {
        const b = vals.buyVol || 0;
        const s = vals.sellVol || 0;
        const total = b + s;
        const vpin = Math.abs(b - s) / total;
        let interpretation = 'Normal Microstructure Flow';
        if (vpin > 0.65) interpretation = '⚠️ High Toxicity (Adverse Selection Risk)';
        else if (vpin > 0.45) interpretation = 'Moderate Informed Flow';
        return {
          result: vpin.toFixed(4),
          label: 'VPIN Metric',
          interpretation,
        };
      },
    },
  },
  {
    id: 'microprice',
    title: 'Micro-Price & Queue Imbalance Drift',
    subtitle: 'Stoikov Volume-Weighted Fair Value Price',
    formula: 'P* = S_a * (V_b / (V_b + V_a)) + S_b * (V_a / (V_b + V_a))',
    latexDoc: 'P_t^* = S_t^a \\cdot \\frac{V_t^b}{V_t^b + V_t^a} + S_t^b \\cdot \\frac{V_t^a}{V_t^b + V_t^a}',
    latexDisplay: 'P_t^* = S_t^a \\cdot \\frac{V_t^b}{V_t^b + V_t^a} + S_t^b \\cdot \\frac{V_t^a}{V_t^b + V_t^a}',
    description: 'Computes the fair expectation of the next price tick based on queue sizes at the top bid and offer, outperforming simple mid-price.',
    institutionalUtility: 'Eliminates mark-to-market lag in execution algorithms by predicting next tick direction prior to trade execution.',
    params: [
      { name: 'S_t^a', desc: 'Current Best Ask Price' },
      { name: 'S_t^b', desc: 'Current Best Bid Price' },
      { name: 'V_t^b', desc: 'Best Bid Queue Volume' },
      { name: 'V_t^a', desc: 'Best Ask Queue Volume' },
    ],
    interactiveDemo: {
      label: 'Micro-Price Estimator',
      inputs: [
        { name: 'bidPrice', min: 100, max: 500, step: 0.05, default: 2450.00, symbol: 'Best Bid ($)' },
        { name: 'askPrice', min: 100, max: 500, step: 0.05, default: 2450.25, symbol: 'Best Ask ($)' },
        { name: 'bidVol', min: 100, max: 10000, step: 100, default: 8000, symbol: 'Bid Queue' },
        { name: 'askVol', min: 100, max: 10000, step: 100, default: 2000, symbol: 'Ask Queue' },
      ],
      calc: (vals) => {
        const sb = vals.bidPrice || 2450.00;
        const sa = vals.askPrice || 2450.25;
        const vb = vals.bidVol || 1;
        const va = vals.askVol || 1;
        const micro = sa * (vb / (vb + va)) + sb * (va / (vb + va));
        const mid = (sb + sa) / 2;
        const delta = micro - mid;
        return {
          result: `₹${micro.toFixed(2)}`,
          label: 'Micro-Price Fair Value',
          interpretation: `Drift from Mid-Price: ${delta >= 0 ? '+' : ''}${delta.toFixed(3)} pts`,
        };
      },
    },
  },
  {
    id: 'hawkes',
    title: 'Hawkes Self-Exciting Point Process',
    subtitle: 'High-Frequency Order Clustering & Intensity',
    formula: 'lambda(t) = mu + sum(alpha * exp(-beta * (t - t_i)))',
    latexDoc: '\\lambda(t) = \\mu + \\sum_{t_i < t} \\alpha e^{-\\beta (t - t_i)}',
    latexDisplay: '\\lambda(t) = \\mu + \\sum_{t_i < t} \\alpha e^{-\\beta (t - t_i)}',
    description: 'Models endogenous order arrival clustering where every execution event increases the probability of subsequent trade bursts in the immediate future.',
    institutionalUtility: 'Dynamic order placement timing: delays liquidity provision during high-intensity Hawkes cascades to prevent toxic flow absorption.',
    params: [
      { name: '\\mu', desc: 'Baseline exogenous trade arrival rate' },
      { name: '\\alpha', desc: 'Self-excitation coefficient (magnitude of impact per trade)' },
      { name: '\\beta', desc: 'Exponential decay rate of event memory' },
      { name: 't_i', desc: 'Timestamp of historical event i' },
    ],
  },
];

export const MathFoundations: React.FC = () => {
  const [activeConceptId, setActiveConceptId] = useState<string>('obi');
  const [sliderValues, setSliderValues] = useState<Record<string, number>>({});

  const activeConcept = CONCEPTS.find((c) => c.id === activeConceptId) || CONCEPTS[0];

  const handleInputChange = (name: string, val: number) => {
    setSliderValues((prev) => ({ ...prev, [name]: val }));
  };

  // Resolve current values for active demo
  const currentDemoValues = React.useMemo(() => {
    if (!activeConcept.interactiveDemo) return {};
    const defaults: Record<string, number> = {};
    activeConcept.interactiveDemo.inputs.forEach((inp) => {
      defaults[inp.name] = sliderValues[inp.name] !== undefined ? sliderValues[inp.name] : inp.default;
    });
    return defaults;
  }, [activeConcept, sliderValues]);

  const demoOutput = activeConcept.interactiveDemo
    ? activeConcept.interactiveDemo.calc(currentDemoValues)
    : null;

  return (
    <div className="bg-slate-900/80 border border-slate-800 rounded-2xl p-6 shadow-2xl backdrop-blur-xl transform-gpu">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6 pb-4 border-b border-slate-800">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="px-2.5 py-0.5 rounded-full text-xs font-mono font-semibold bg-cyan-500/10 text-cyan-400 border border-cyan-500/20 flex items-center gap-1">
              <Binary className="w-3 h-3" /> QUANTITATIVE MATHEMATICS
            </span>
            <span className="text-xs text-slate-400 font-mono">Market Microstructure Theory (MMIP)</span>
          </div>
          <h3 className="text-2xl font-bold text-white tracking-tight">
            Mathematical Foundations & Pricing Models
          </h3>
          <p className="text-slate-400 text-sm mt-1">
            Stochastic point processes, order imbalance metrics, and adverse selection probability models.
          </p>
        </div>
      </div>

      {/* Tabs for Math Concepts */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-2 mb-6">
        {CONCEPTS.map((c) => {
          const isActive = c.id === activeConceptId;
          return (
            <button
              key={c.id}
              onClick={() => setActiveConceptId(c.id)}
              className={`p-3 rounded-xl border text-left transition-all ${
                isActive
                  ? 'bg-cyan-950/40 border-cyan-500/50 shadow-lg shadow-cyan-950/50 text-white'
                  : 'bg-slate-950/50 border-slate-800/80 text-slate-400 hover:border-slate-700 hover:text-slate-200'
              }`}
            >
              <div className="font-semibold text-sm truncate">{c.title.split(' (')[0]}</div>
              <div className="text-xs text-slate-400 truncate mt-0.5">{c.subtitle}</div>
            </button>
          );
        })}
      </div>

      {/* Concept Details & Formula Block */}
      <AnimatePresence mode="wait">
        <motion.div
          key={activeConcept.id}
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: -8 }}
          transition={{ duration: 0.25 }}
          className="grid grid-cols-1 lg:grid-cols-12 gap-6"
        >
          {/* Left Column: Equations & Theory */}
          <div className="lg:col-span-7 space-y-4">
            <div className="bg-slate-950 p-5 rounded-xl border border-slate-800">
              <div className="flex items-center justify-between mb-3">
                <span className="text-xs font-mono text-cyan-400 uppercase font-semibold">FORMULA DERIVATION</span>
                <span className="text-xs font-mono text-slate-500">{activeConcept.subtitle}</span>
              </div>

              {/* Display Box */}
              <div className="py-4 px-6 rounded-lg bg-slate-900/90 border border-cyan-500/20 text-center font-mono text-lg text-cyan-300 font-bold tracking-wide shadow-inner overflow-x-auto">
                {activeConcept.formula}
              </div>

              <p className="text-slate-300 text-sm mt-4 leading-relaxed">
                {activeConcept.description}
              </p>
            </div>

            {/* Institutional Utility Card */}
            <div className="p-4 rounded-xl bg-cyan-950/20 border border-cyan-500/20 flex items-start gap-3">
              <div className="p-2 rounded-lg bg-cyan-500/10 border border-cyan-500/20 text-cyan-400 mt-0.5">
                <Lightbulb className="w-4 h-4" />
              </div>
              <div>
                <h4 className="text-xs font-mono uppercase font-semibold text-cyan-400">
                  INSTITUTIONAL ALGORITHMIC APPLICATION
                </h4>
                <p className="text-sm text-slate-300 mt-1">
                  {activeConcept.institutionalUtility}
                </p>
              </div>
            </div>

            {/* Parameters list */}
            <div className="bg-slate-950/60 p-4 rounded-xl border border-slate-800">
              <h5 className="text-xs font-mono uppercase text-slate-400 mb-2 font-semibold">Variable Specifications</h5>
              <div className="space-y-2">
                {activeConcept.params.map((p) => (
                  <div key={p.name} className="flex items-start gap-2 text-xs">
                    <span className="font-mono text-cyan-400 bg-cyan-950/60 px-1.5 py-0.5 rounded border border-cyan-500/20 font-bold">
                      {p.name}
                    </span>
                    <span className="text-slate-300">{p.desc}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Right Column: Interactive Parameter Simulator */}
          <div className="lg:col-span-5 bg-slate-950 p-5 rounded-xl border border-slate-800 flex flex-col justify-between">
            {activeConcept.interactiveDemo ? (
              <div className="space-y-4">
                <div className="flex items-center justify-between pb-3 border-b border-slate-800">
                  <div className="flex items-center gap-2">
                    <Calculator className="w-4 h-4 text-cyan-400" />
                    <span className="text-sm font-semibold text-white">
                      {activeConcept.interactiveDemo.label}
                    </span>
                  </div>
                  <span className="text-xs font-mono text-emerald-400 bg-emerald-500/10 px-2 py-0.5 rounded border border-emerald-500/20">
                    Live Calculation
                  </span>
                </div>

                {/* Input Controls */}
                <div className="space-y-3">
                  {activeConcept.interactiveDemo.inputs.map((inp) => {
                    const val = currentDemoValues[inp.name];
                    return (
                      <div key={inp.name} className="space-y-1">
                        <div className="flex justify-between text-xs">
                          <span className="text-slate-300 font-medium">{inp.symbol}</span>
                          <span className="font-mono text-cyan-400 font-semibold">{val}</span>
                        </div>
                        <input
                          type="range"
                          min={inp.min}
                          max={inp.max}
                          step={inp.step}
                          value={val}
                          onChange={(e) => handleInputChange(inp.name, parseFloat(e.target.value))}
                          className="w-full h-1.5 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-cyan-400"
                        />
                      </div>
                    );
                  })}
                </div>

                {/* Output Screen */}
                {demoOutput && (
                  <div className="mt-4 p-4 rounded-xl bg-slate-900 border border-cyan-500/30 text-center space-y-2">
                    <span className="text-xs font-mono uppercase text-slate-400 block">{demoOutput.label}</span>
                    <div className="text-3xl font-mono font-bold text-cyan-300">
                      {demoOutput.result}
                    </div>
                    <div className="text-xs font-medium text-emerald-400 bg-emerald-950/40 py-1 px-3 rounded-md border border-emerald-500/20 inline-block">
                      {demoOutput.interpretation}
                    </div>
                  </div>
                )}
              </div>
            ) : (
              <div className="h-full flex flex-col items-center justify-center text-center p-6 space-y-3">
                <div className="p-3 rounded-full bg-slate-900 text-cyan-400 border border-slate-800">
                  <TrendingUp className="w-8 h-8" />
                </div>
                <h4 className="text-sm font-semibold text-white">Hawkes Process Simulation</h4>
                <p className="text-xs text-slate-400">
                  Hawkes process parameters (\mu, \alpha, \beta) are updated in real-time by the Java 21 LMAX disruptor thread when processing book tick bursts.
                </p>
                <div className="p-3 rounded-lg bg-slate-900 border border-slate-800 w-full text-left font-mono text-xs text-cyan-400 space-y-1">
                  <div>\mu = 0.05 arrivals/ms</div>
                  <div>\alpha = 0.85 decay excitation</div>
                  <div>\beta = 1.25 memory scale</div>
                </div>
              </div>
            )}

            <div className="pt-4 border-t border-slate-800 text-center">
              <span className="text-xs font-mono text-slate-500">
                Verified against Level-3 ITCH/OUCH market protocol specs
              </span>
            </div>
          </div>
        </motion.div>
      </AnimatePresence>
    </div>
  );
};
